import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import './AgentRequestsPage.css';

const API_BASE = 'http://localhost:8000/api/v1';

const STATUS_COLORS = {
  pending: '#f59e0b',
  approved: '#10b981',
  rejected: '#ef4444',
  executed: '#3b82f6',
};

const REQUEST_TYPE_ICONS = {
  reorder: '📦',
  price_update: '💲',
  dead_stock_discount: '🏷️',
  anomaly_flag: '⚠️',
  transaction_block: '🚫',
  product_create: '➕',
  bulk_update: '🔄',
};

export default function AgentRequestsPage() {
  const { getToken } = useAuth();
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all');
  const [selectedRequest, setSelectedRequest] = useState(null);
  const [reviewNotes, setReviewNotes] = useState('');
  const [processing, setProcessing] = useState(false);

  const fetchRequests = async () => {
    setLoading(true);
    try {
      const token = getToken();
      const url = filter === 'all'
        ? `${API_BASE}/agent-requests?limit=100`
        : `${API_BASE}/agent-requests?status=${filter}&limit=100`;

      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      setRequests(data);
    } catch (err) {
      console.error('Failed to fetch requests:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRequests();
  }, [filter]);

  const handleReview = async (requestId, status) => {
    setProcessing(true);
    try {
      const token = getToken();
      const res = await fetch(`${API_BASE}/agent-requests/${requestId}/review`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ status, notes: reviewNotes }),
      });

      if (res.ok) {
        fetchRequests();
        setSelectedRequest(null);
        setReviewNotes('');
      } else {
        const err = await res.json();
        alert(`Failed to review: ${err.detail}`);
      }
    } catch (err) {
      console.error('Review failed:', err);
    } finally {
      setProcessing(false);
    }
  };

  const formatDate = (dateStr) => {
    const date = new Date(dateStr);
    return date.toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <div className="agent-requests-page">
      <div className="page-header">
        <h1>📋 Agent Requests</h1>
        <p>Review and approve actions generated by AI agents</p>
      </div>

      <div className="filter-bar">
        <button
          className={filter === 'all' ? 'active' : ''}
          onClick={() => setFilter('all')}
        >
          All
        </button>
        <button
          className={filter === 'pending' ? 'active' : ''}
          onClick={() => setFilter('pending')}
        >
          ⏳ Pending
        </button>
        <button
          className={filter === 'approved' ? 'active' : ''}
          onClick={() => setFilter('approved')}
        >
          ✅ Approved
        </button>
        <button
          className={filter === 'rejected' ? 'active' : ''}
          onClick={() => setFilter('rejected')}
        >
          ❌ Rejected
        </button>
        <button
          className={filter === 'executed' ? 'active' : ''}
          onClick={() => setFilter('executed')}
        >
          ✔️ Executed
        </button>
      </div>

      {loading ? (
        <div className="loading">Loading requests...</div>
      ) : requests.length === 0 ? (
        <div className="empty-state">
          <p>No requests found</p>
        </div>
      ) : (
        <div className="requests-grid">
          {requests.map((req) => (
            <div
              key={req.id}
              className={`request-card ${req.status}`}
              onClick={() => setSelectedRequest(req)}
            >
              <div className="card-header">
                <span className="request-icon">
                  {REQUEST_TYPE_ICONS[req.request_type] || '📄'}
                </span>
                <span
                  className="status-badge"
                  style={{ backgroundColor: STATUS_COLORS[req.status] }}
                >
                  {req.status}
                </span>
              </div>

              <h3 className="request-title">{req.title}</h3>
              <p className="request-type">{req.request_type.replace(/_/g, ' ')}</p>

              <div className="card-meta">
                <span>🤖 {req.agent_name}</span>
                <span>📅 {formatDate(req.created_at)}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {selectedRequest && (
        <div className="modal-overlay" onClick={() => setSelectedRequest(null)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <button className="close-btn" onClick={() => setSelectedRequest(null)}>
              ✕
            </button>

            <div className="modal-header">
              <span className="request-icon">
                {REQUEST_TYPE_ICONS[selectedRequest.request_type] || '📄'}
              </span>
              <h2>{selectedRequest.title}</h2>
            </div>

            <div className="modal-body">
              <div className="detail-row">
                <label>Status:</label>
                <span
                  className="status-badge"
                  style={{ backgroundColor: STATUS_COLORS[selectedRequest.status] }}
                >
                  {selectedRequest.status}
                </span>
              </div>

              <div className="detail-row">
                <label>Agent:</label>
                <span>{selectedRequest.agent_name}</span>
              </div>

              <div className="detail-row">
                <label>Type:</label>
                <span>{selectedRequest.request_type}</span>
              </div>

              <div className="detail-row">
                <label>Created:</label>
                <span>{formatDate(selectedRequest.created_at)}</span>
              </div>

              {selectedRequest.entity_type && (
                <div className="detail-row">
                  <label>Entity:</label>
                  <span>{selectedRequest.entity_type} ({selectedRequest.entity_id?.slice(0, 8)}...)</span>
                </div>
              )}

              <div className="detail-full">
                <label>Description:</label>
                <p>{selectedRequest.description}</p>
              </div>

              <div className="detail-full">
                <label>Proposed Action:</label>
                <p className="proposed-action">{selectedRequest.proposed_action}</p>
              </div>

              {selectedRequest.impact_summary && (
                <div className="detail-full">
                  <label>Impact Summary:</label>
                  <p>{selectedRequest.impact_summary}</p>
                </div>
              )}

              {selectedRequest.request_data && (
                <div className="detail-full">
                  <label>Request Data:</label>
                  <pre className="request-data">
                    {JSON.stringify(selectedRequest.request_data, null, 2)}
                  </pre>
                </div>
              )}

              {selectedRequest.status === 'pending' && (
                <div className="review-section">
                  <label>Review Notes:</label>
                  <textarea
                    value={reviewNotes}
                    onChange={(e) => setReviewNotes(e.target.value)}
                    placeholder="Add notes about your decision..."
                    rows={3}
                  />

                  <div className="review-actions">
                    <button
                      className="approve-btn"
                      onClick={() => handleReview(selectedRequest.id, 'approved')}
                      disabled={processing}
                    >
                      ✓ Approve
                    </button>
                    <button
                      className="reject-btn"
                      onClick={() => handleReview(selectedRequest.id, 'rejected')}
                      disabled={processing}
                    >
                      ✗ Reject
                    </button>
                  </div>
                </div>
              )}

              {selectedRequest.reviewed_by && (
                <div className="review-info">
                  <strong>Reviewed by:</strong> {selectedRequest.reviewed_by}
                  <br />
                  <strong>At:</strong> {formatDate(selectedRequest.reviewed_at)}
                  {selectedRequest.review_notes && (
                    <>
                      <br />
                      <strong>Notes:</strong> {selectedRequest.review_notes}
                    </>
                  )}
                </div>
              )}

              {selectedRequest.execution_result && (
                <div className="execution-result">
                  <strong>Execution Result:</strong>
                  <pre>{JSON.stringify(selectedRequest.execution_result, null, 2)}</pre>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
